// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrrtqunnrfvarxyozpiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndycnRxdW5ucmZ2YXJ4eW96cGl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NjEzNzIsImV4cCI6MjA2MjUzNzM3Mn0.tB3rWzYUzplR50icxoSRSGRswwhoQyDrtfgaekIeIgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);